project_id = "oegvwjxrlmtwortyhsrv"

[functions.domain-redirect]
verify_jwt = false

[functions.asn-proxy]
verify_jwt = false

[functions.reverse-ip-proxy]
verify_jwt = false

[functions.seo-analysis]
verify_jwt = false

[functions.asn-content-generator]
verify_jwt = false

[functions.analyze-domain-potential]
verify_jwt = false

[functions.openprovider-domain-check]
verify_jwt = false

[functions.openprovider-domain-purchase]
verify_jwt = false
